spring.application.name=ProductionWorkOrderSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/pwos_db
spring.datasource.username=pwos_user
spring.datasource.password=palak26
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080